// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI flow to review and improve the 'about' section for developers.
 *
 * - improveAboutSection - A function that enhances the about section based on AI suggestions.
 * - ImproveAboutSectionInput - The input type for the improveAboutSection function.
 * - ImproveAboutSectionOutput - The return type for the improveAboutSection function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveAboutSectionInputSchema = z.string().describe('The current about section text.');
export type ImproveAboutSectionInput = z.infer<typeof ImproveAboutSectionInputSchema>;

const ImproveAboutSectionOutputSchema = z.object({
  improvedAboutSection: z
    .string()
    .describe('The improved about section text with suggestions incorporated.'),
  suggestions: z.array(z.string()).describe('Specific suggestions for improvement.'),
});
export type ImproveAboutSectionOutput = z.infer<typeof ImproveAboutSectionOutputSchema>;

export async function improveAboutSection(input: ImproveAboutSectionInput): Promise<ImproveAboutSectionOutput> {
  return improveAboutSectionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveAboutSectionPrompt',
  input: {schema: ImproveAboutSectionInputSchema},
  output: {schema: ImproveAboutSectionOutputSchema},
  prompt: `You are an AI career coach specializing in helping web developers craft compelling "about" sections for their portfolios.

  Analyze the following "about" section and provide an improved version, along with a list of specific suggestions for improvement.

  Original About Section:
  {{input}}

  Improved About Section:
  `, // The LLM will complete this, filling in the `improvedAboutSection` field.
});

const improveAboutSectionFlow = ai.defineFlow(
  {
    name: 'improveAboutSectionFlow',
    inputSchema: ImproveAboutSectionInputSchema,
    outputSchema: ImproveAboutSectionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
